### ISSUE TITLE
can you please see which lesson it is saying I skipped?  it looks like i did all the previous ones

### ISSUE THREAD

**Issue by m-gamao** [learn-co-curriculum/ruby-gets-input#28]

**Comment by maxwellbenton** [comment]
Thank you for and providing this feedback, @guerilla17.

An issue occurred for multiple students over the past day or so and we believe it was caused by an outage on GitHub (https://www.onmsft.com/news/github-suffers-hours-long-outage-coming-back-online-now). As of now, lessons are correctly forking and submitting. It may be that while you've completed the lessons, your work was not successfully pushed to GitHub due to the outage. If you return to recent labs and push up your solutions this problem should be resolved. 

If learn continues to state that you've skipped a lesson, please re-open this issue. 💙
